export const ADD_MEMBER = 'ADD_MEMBER'
export const EDIT_MEMBER = 'EDIT_MEMBER'
export const DELETE_MEMBER = 'DELETE_MEMBER'
export const ADD_ITEMS = 'ADD_ITEMS'
export const DELETE_ITEM = 'DELETE_ITEM'
